.class public final Lcom/facebook/omnistore/mqtt/AutoGeneratedBindingsForOmnistoreMqttModule;
.super Ljava/lang/Object;
.source "AutoGeneratedBindingsForOmnistoreMqttModule.java"


# annotations
.annotation runtime Lcom/facebook/inject/AutoGeneratedBinder;
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    .prologue
    .line 35
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
