.class public final Lcom/facebook/config/application/a;
.super Ljava/lang/Object;
.source "AutoGeneratedBindingsForFbAppTypeModule.java"


# annotations
.annotation runtime Lcom/facebook/inject/AutoGeneratedBinder;
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    .prologue
    .line 19
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
